-- REGION TABLE
CREATE TABLE REGIONS (
    REGION_ID INT PRIMARY KEY,
    REGION_NAME VARCHAR(100)
);

-- COUNTRY TABLE
CREATE TABLE COUNTRIES (
    COUNTRY_ID VARCHAR(2) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(100),
    REGION_ID INT,
    CONSTRAINT FK_COUNTRY_REGION FOREIGN KEY (REGION_ID)
        REFERENCES REGIONS(REGION_ID)
);

-- LOCATION TABLE
CREATE TABLE LOCATIONS (
    LOCATION_ID INT PRIMARY KEY,
    STREET_ADDRESS VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    CITY VARCHAR(100),
    STATE_PROVINCE VARCHAR(100),
    COUNTRY_ID VARCHAR(2),
    CONSTRAINT FK_LOCATION_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES COUNTRIES(COUNTRY_ID)
);